---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-homework
  namespace: homework
data:
  homework.conf: |
    server {
        listen 8000;
        server_name localhost;

        location /homepage {
          root /homework;
          index index.html;
        }

        location ~ /\.ht {
          deny all;
        }
    }
