repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kafka
    url: oci://registry-1.docker.io/bitnamicharts/kafka
    oci: true