---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator
rules:
  - apiGroups:
      - otus.homework
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - apps
    resources: 
      - replicasets
      - deployments
      - pods
    verbs: ["*"]
  - apiGroups:
      - ''
    resources:
      - nodes
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
      - service
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["*"]
