apiVersion: otus.homework/v1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-sample
    app.kubernetes.io/part-of: mysql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql
  name: mysql-sample
spec:
  # TODO(user): Add fields here
  name: mysql-operator
  message: "Hello, World"
  image: "mysql:8.3.0"
  database: "test"
  password: "password"
  storage_size: "1Gi"

