---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    resourceNames: ["metrics-server"]
    verbs:
      - get
      - list
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get