---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    component: homework
    app: ui
  namespace: homework
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: nginx
    component: homework
