---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-homework
  namespace: homework
data:
  homework.conf: |
    server {
        listen 8000;
        server_name localhost;

        location / {
          root /homework;
          index index.html index.htm;
        }

        location ~ /\.ht {
          deny all;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-env
  namespace: homework
data:
  http_port: "8000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-file
  namespace: homework
data:
  file: |-
    property=value