---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: homework-storage
  hostPath:
    path: "/data/homework-volume"