apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homework-storage
  resources:
    requests:
      storage: 100Mi
  volumeName: homework-pv
