apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  ports:
  - port: 8000
    name: plaintext
    targetPort: 80
  selector:
    app: http
  type: LoadBalancer
  externalTrafficPolicy: Cluster
